# Basic configuration
base_url = "https://arvedbloecker.de"
title = "Arved Blöcker"
description = "Personal blog of Arved Blöcker"
default_language = "en"

# Build configuration
compile_sass = true
build_search_index = true
generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
# Custom variables that can be used in templates
author = "Arved Blöcker"
